[project]
name = "strides-backend"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "fastapi[all]",
    "motor",
    "passlib[bcrypt]",
    "python-dotenv>=1.1.0",
    "python-jose",
    "requests>=2.32.4",
]
